function [saccade_table] = eye_tracking_file_OA(experiment_name)


% THIS PART IS NECESSARY TO MAKE THE IMAGE NAME IMPORT AS A STRING AND
% NOT JUST NaN
opts            = detectImportOptions(experiment_name);
opts            = setvartype(opts, {...
    'RecordingTimestamp', ...
    'EyeTrackerTimestamp', ...
    'FixationIndex', ...
    'SaccadeIndex', ...
    'GazeEventDuration', ...
    'FixationPointX_MCSpx_', ...
    'FixationPointY_MCSpx_', ...
    'SaccadicAmplitude', ...
    'AbsoluteSaccadicDirection', ...
    'RelativeSaccadicDirection', ...
    'GazePointIndex', ...
    'GazePointLeftX_ADCSpx_', ...
    'GazePointLeftY_ADCSpx_', ...
    'GazePointRightX_ADCSpx_', ...
    'GazePointRightY_ADCSpx_', ...
    'GazePointX_ADCSpx_', ...
    'GazePointX_ADCSpx_', ...
    'GazePointX_MCSpx_', ...
    'GazePointY_MCSpx_', ...
    'GazePointLeftX_ADCSmm_', ...
    'GazePointLeftY_ADCSmm_', ...
    'GazePointRightX_ADCSmm_', ...
    'GazePointRightY_ADCSmm_', ...
    'StrictAverageGazePointX_ADCSmm_', ...
    'StrictAverageGazePointY_ADCSmm_', ...
    'PupilLeft', ...
    'PupilRight', ...
    'ValidityLeft', ...
    'ValidityRight', ...
    'RecordingTimestamp'}, 'double');

saccade_table_all   = readtable(experiment_name, opts);

% Remove unnecessary AOI information
aoi_idx                         = contains(saccade_table_all.Properties.VariableNames', 'AOI');
saccade_table_all(:,aoi_idx)    = [];

RecordingTimestamp              = saccade_table_all.RecordingTimestamp;
EyeTrackerTimestamp             = saccade_table_all.EyeTrackerTimestamp;
FixationIndex                   = saccade_table_all.FixationIndex;
SaccadeIndex                    = saccade_table_all.SaccadeIndex;
GazeEventType                   = saccade_table_all.GazeEventType;
GazeEventDuration               = saccade_table_all.GazeEventDuration;
FixationPointX_MCSpx_           = saccade_table_all.FixationPointX_MCSpx_;
FixationPointY_MCSpx_           = saccade_table_all.FixationPointY_MCSpx_;
SaccadicAmplitude               = saccade_table_all.SaccadicAmplitude;
AbsoluteSaccadicDirection       = saccade_table_all.AbsoluteSaccadicDirection;
RelativeSaccadicDirection       = saccade_table_all.RelativeSaccadicDirection;
GazePointIndex                  = saccade_table_all.GazePointIndex;
GazePointLeftX_ADCSpx_          = saccade_table_all.GazePointLeftX_ADCSpx_;
GazePointLeftY_ADCSpx_          = saccade_table_all.GazePointLeftY_ADCSpx_;
GazePointRightX_ADCSpx_         = saccade_table_all.GazePointRightX_ADCSpx_;
GazePointRightY_ADCSpx_         = saccade_table_all.GazePointRightY_ADCSpx_;
GazePointX_ADCSpx_              = saccade_table_all.GazePointX_ADCSpx_;
GazePointY_ADCSpx_              = saccade_table_all.GazePointY_ADCSpx_;
GazePointX_MCSpx_               = saccade_table_all.GazePointX_MCSpx_;
GazePointY_MCSpx_               = saccade_table_all.GazePointY_MCSpx_;
GazePointLeftX_ADCSmm_          = saccade_table_all.GazePointLeftX_ADCSmm_;
GazePointLeftY_ADCSmm_          = saccade_table_all.GazePointLeftY_ADCSmm_;
GazePointRightX_ADCSmm_         = saccade_table_all.GazePointRightX_ADCSmm_;
GazePointRightY_ADCSmm_         = saccade_table_all.GazePointRightY_ADCSmm_;
StrictAverageGazePointX_ADCSmm_ = saccade_table_all.StrictAverageGazePointX_ADCSmm_;
StrictAverageGazePointY_ADCSmm_ = saccade_table_all.StrictAverageGazePointY_ADCSmm_;
PupilLeft                       = saccade_table_all.PupilLeft;
PupilRight                      = saccade_table_all.PupilRight;
ValidityLeft                    = saccade_table_all.ValidityLeft;
ValidityRight                   = saccade_table_all.ValidityRight;
MediaName                       = saccade_table_all.MediaName;

saccade_table = table(...
    RecordingTimestamp, ...
    EyeTrackerTimestamp, ...
    FixationIndex, ...
    SaccadeIndex, ...
    GazeEventType, ...
    GazeEventDuration, ...
    FixationPointX_MCSpx_, ...
    FixationPointY_MCSpx_, ...
    SaccadicAmplitude, ...
    AbsoluteSaccadicDirection, ...
    RelativeSaccadicDirection, ...
    GazePointIndex, ...
    GazePointLeftX_ADCSpx_, ...
    GazePointLeftY_ADCSpx_, ...
    GazePointRightX_ADCSpx_, ...
    GazePointRightY_ADCSpx_, ...
    GazePointX_ADCSpx_, ...
    GazePointY_ADCSpx_, ...
    GazePointX_MCSpx_, ...
    GazePointY_MCSpx_, ...
    GazePointLeftX_ADCSmm_, ...
    GazePointLeftY_ADCSmm_, ...
    GazePointRightX_ADCSmm_, ...
    GazePointRightY_ADCSmm_, ...
    StrictAverageGazePointX_ADCSmm_, ...
    StrictAverageGazePointY_ADCSmm_, ...
    PupilLeft, ...
    PupilRight, ...
    ValidityLeft, ...
    ValidityRight, ...
    MediaName);


end
